export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLE = "GET_ARTICLE";
export const ADD_ARTICLE = "ADD_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLES";
export const ARTICLES_LOADING = "ARTICLES_LOADING";

export const GET_AUTHOR = "GET_AUTHOR";
export const AUTHORS_LOADING = "AUTHORS_LOADING";
